name: 提交会议
description: 提交核物理会议信息
title: "[会议] "
labels: ["conference"]
body:
  - type: input
    id: title
    attributes:
      label: 会议名称
      placeholder: 例如：全国核物理大会
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 地点
      placeholder: 例如：北京
    validations:
      required: true

  - type: input
    id: start_date
    attributes:
      label: 开始日期
      placeholder: 2026-05-12
    validations:
      required: true

  - type: input
    id: end_date
    attributes:
      label: 结束日期
      placeholder: 2026-05-16
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 官网链接
      placeholder: https://...
    validations:
      required: true

  - type: textarea
    id: note
    attributes:
      label: 备注（可选）
      placeholder: 例如：国际会议等
